services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: ai-support-postgres

    environment:
      POSTGRES_DB: ai_support
      POSTGRES_USER: ai_support
      POSTGRES_PASSWORD: ai_support

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ai_support -d ai_support" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: